Add routes section to docs
geut/permanent-seeder pull request #125
Opened 2020-10-07 18:24 UTC by chartgerink

Thanks to @dpaez, I was able to find this route again. I am adding this to the docs so it doesn't require me pinging @dpaez every so often :)﻿

2020-10-08 07:45 UTC, juliangruber requested changes

2020-10-08 07:45 UTC, juliangruber commented on README.md
> +The route `api/raw/:key` displays the raw data that feed into the dashboard.
```suggestion
Returns the raw data that feed into the dashboard.
```

less redundant

2020-10-08 10:19 UTC, juliangruber approved these changes

2020-10-21 22:30 UTC, merged

2020-10-21 22:31 UTC, estebanprimost commented
Thanks @chartgerink + @juliangruber :rocket: :rocket: